from aiogram.fsm.state import State, StatesGroup


class ClientFlow(StatesGroup):
    name = State()
    age = State()
    minor_confirm = State()
    height = State()
    weight = State()
    contact = State()
    contact_phone = State()
    no_username = State()
    motorcycle_class = State()
    route = State()
    route_individual = State()
    date = State()
    time_slot = State()
    pickup_type = State()
    pickup_method = State()
    pickup_address = State()
    pickup_location = State()
    confirm = State()
    edit_field = State()


class RiderFlow(StatesGroup):
    name = State()
    age = State()
    seasons = State()
    motorcycle_class = State()
    motorcycle_model = State()
    equipment = State()
    max_passenger_weight = State()
    can_pickup_client = State()
    can_ride_night = State()
    can_individual_route = State()
    base_area = State()
    comment = State()
    photos = State()
    confirm = State()


class AdminFlow(StatesGroup):
    message_target = State()
    reject_client = State()
    reject_rider = State()
    manual_rider_name = State()
    manual_rider_username = State()
    manual_rider_telegram_id = State()
    manual_rider_age = State()
    manual_rider_seasons = State()
    manual_rider_motorcycle_class = State()
    manual_rider_motorcycle_model = State()
    manual_rider_equipment = State()
    manual_rider_max_passenger_weight = State()
    manual_rider_can_pickup_client = State()
    manual_rider_can_ride_night = State()
    manual_rider_can_individual_route = State()
    manual_rider_base_area = State()
    manual_rider_comment = State()
    manual_rider_photos = State()
    manual_rider_confirm = State()
